version : '3'
services:
  app:
    image: spring/gs-spring-boot-docker
    volumes:
      - /docker_deploy/log/blue:/var/app/log
    ports:
      - 8010:8080
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
